export const GET_MEMBER_BALANCES = "GET_MEMBER_BALANCES";
export const GET_MEMBER_BALANCES_SUCCESS = "GET_MEMBER_BALANCES_SUCCESS";
export const GET_MEMBER_BALANCES_FAILURE = "GET_MEMBER_BALANCES_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
