export const GET_LOAN_TYPES = "GET_LOAN_TYPES";
export const GET_LOAN_TYPES_SUCCESS = "GET_LOAN_TYPES_SUCCESS";
export const GET_LOAN_TYPES_FAILURE = "GET_LOAN_TYPES_FAILURE";
export const GET_GUARANTOR_REQUESTS = "GET_GUARANTOR_REQUESTS";
export const GET_GUARANTOR_REQUESTS_SUCCESS = "GET_GUARANTOR_REQUESTS_SUCCESS";
export const GET_GUARANTOR_REQUESTS_FAILURE = "GET_GUARANTOR_REQUESTS_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
