export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
export const USER_LOGOUT = "USER_LOGOUT";
