export const UPDATE_PROFILE_INFO = "UPDATE_PROFILE_INFO";
export const UPDATE_PROFILE_INFO_SUCCESS = "UPDATE_PROFILE_INFO_SUCCESS";
export const UPDATE_PROFILE_INFO_FAILURE = "UPDATE_PROFILE_INFO_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
