export const CHANGE_BALANCE = "CHANGE_BALANCE_BALANCES";
export const CHANGE_BALANCE_SUCCESS = "CHANGE_BALANCE_SUCCESS";
export const CHANGE_BALANCE_FAILURE = "CHANGE_BALANCE_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
