export const SEND_SUPPORT_MAIL = "SEND_SUPPORT_MAIL";
export const SEND_SUPPORT_MAIL_SUCCESS = "SEND_SUPPORT_MAIL_SUCCESS";
export const SEND_SUPPORT_MAIL_FAILURE = "SEND_SUPPORT_MAIL_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
