export const UPDATE_KIN_INFO = "UPDATE_KIN_INFO";
export const UPDATE_KIN_INFO_SUCCESS = "UPDATE_KIN_INFO_SUCCESS";
export const UPDATE_KIN_INFO_FAILURE = "UPDATE_KIN_INFO_FAILURE";
export const GET_KIN_INFO = "GET_KIN_INFO";
export const GET_KIN_INFO_SUCCESS = "GET_KIN_INFO_SUCCESS";
export const GET_KIN_INFO_FAILURE = "GET_KIN_INFO_FAILURE";
export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
